### ISSUE TITLE
Mac auto-restarting using 10.11.6, Casper Imaging 9.93, JSS 9.93 on AutoCasperNBI 1.3.3 created NetBoot

### ISSUE THREAD

**Issue by hkabik** [macmule/AutoCasperNBI#83] opened 2016-08-29 20:10 UTC
After booting to the netboot Macs auto-restart after a few seconds. Casper Imaging never gets a chance to completes login.

Os - 10.11.6
JSS and Casper Imaging - 9.93
AutoCasperNBI - 1.3.3

**Comment by macmule** [comment] 2016-08-29 21:06
Odd. 

Not seeing that at all.

Have deployed it to a few sites now.

Can you recreate the NBI & check "create restorable dmg" then restore that to a external disk & boot off of that? Hopefully the issue reoccurs & we can have a look at the logs. 

Regards,

Ben.

**Comment by hkabik** [comment] 2016-08-29 22:57
So upon Recreating the NBI, the new one works. They are identical, but if I boot to one the behavior exists and if I boot to the other it's fine. Corruption maybe? Either way, I'm technically resolved. Let me know if you want me to gather any info from the bad nbi before I trash it.

**Comment by entusdictus** [comment] 2016-09-09 08:27
I can confirm this issue. I have tried to build 10.10.5 NBIs and 10.11.6 NBIs, both with Casper Imaging 9.93. Confirmed for multiple customers. One customer doesn't either work after building six NBIs. 
The OS DMGs are all built with AutoDMG and were definitely working when creating previous images.

Please let me know if I should provide any logs for you.

**Comment by macmule** [comment] 2016-09-09 13:07
Hi @hkabik & @entusdictus,

In the NBI folder, do you have the .restorable.dmg? (on the NBI Server).

**Comment by entusdictus** [comment] 2016-09-09 13:09
Yes, the restorable.dmg is in the NBI folder in my case.

**Comment by macmule** [comment] 2016-09-09 15:25
@entusdictus Remove it.. then it'll work.

**Comment by macmule** [comment] 2016-09-09 15:29
Related to: https://jamfnation.jamfsoftware.com/discussion.html?id=19850

**Comment by macmule** [comment] 2016-09-09 15:33
I this: https://github.com/macmule/AutoCasperNBI/issues/87 would stop this happening again.

The NetBoot.restorable.dmg is for disk media, not for NetBoot.

**Comment by macmule** [comment] 2016-09-09 23:14
Hi all,

Please test [this pre-release of AutoCasperNBI](https://github.com/macmule/AutoCasperNBI/releases/tag/1.3.4)

I have restructured the folders that AutoCasperNBI puts items into, to avoid this issue in the future:

![screenshot 2016-09-09 23 30 08](https://cloud.githubusercontent.com/assets/2464974/18405625/7793beb4-76eb-11e6-92ba-8ae5f762d801.png)

The restorable.dmg should only be for removable media.

**Comment by entusdictus** [comment] 2016-09-12 09:34
@macmule: works perfect, thanks! strange issue because we used to let the .restorable.dmg in the NBI folder for several releases now...

**Comment by macmule** [comment] 2016-09-12 11:48
@entusdictus it shouldn't be in there on the NBI server.. i'm guessing you're using a NetSUS or something other an Apple's NetBoot server?

They don't read the NBImageInfo.plist to get the actual DMG, just grep/awk/cut to get an DMG.

But, awesome this is fixed. Closing off.

**Closed by macmule** 2016-09-12 11:48 UTC
Labels: bug
