### ISSUE TITLE
Error Deleting dockfixup in 10.11

### ISSUE THREAD

**Issue by MScottBlake** [macmule/AutoCasperNBI#62] opened 2015-10-01 00:10 UTC
Received the following error building 10.11.0 with JSS 9.81 on a 10.11.0 host. <img width="484" alt="screenshot 2015-09-30 20 06 07" src="https://cloud.githubusercontent.com/assets/945258/10209925/e1d57990-67ae-11e5-877d-fc92d4a84ed7.png">

DMG built with AutoDMG 1.5.3; no extra packages or updates.
NBI built with ACNBI 1.2.1; no extra packages or certs.

**Comment by macmule** [comment] 2015-10-02 07:08
Dupe of https://github.com/macmule/AutoCasperNBI/issues/58 (which i've now made more visible)

**Closed by macmule** 2015-10-02 07:08 UTC
Labels: duplicate
